version: 2
jobs:
  build:
    docker:
      - image: pandoc/core
    steps:
      - run: "apk add git graphviz make openssh-client texlive-full ttf-inconsolata"

      - checkout

      # Build our documents.
      - run: make all
      - store_artifacts:
          path: build
