jobs:
  build:
    docker:
      - image: docker pull jpbernius/pandoc
    steps:
      - checkout
      - run:
          name: Build
          command: make all
      - store_artifacts:
          path: build
