version: 2
jobs:
  build:
    docker:
      - image: pandoc/latex
    steps:
      - checkout
      - run: "apk add graphviz make texlive texmf-dist-latexextra"

      # Build our documents.
      - run: make all
      - store_artifacts:
          path: build
